### ISSUE TITLE
CodeCommit is deprecated, and install script relies on codecommit

### ISSUE THREAD

**Issue by bschwarz** [aws-samples/aws-saas-factory-eks-reference-architecture#102]
install.sh uses CodeCommit. However, CodeCommit has been deprecated, and no new repos can be added. Hence the script will fail.

**Comment by tobuck-aws** [comment]
@bschwarz thanks for the issue. We'll work to fix. Any suggestions jump to mind? At first blush, I think we're considering sourcing the [TenantOnboarding's CodeBuild project](https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/415b599cb1b2178f66131fdd171136cfaf9cd48e/lib/constructs/tenant-onboarding.ts#L61) from [S3](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.Source.html#static-s3props) (vs. [CodeCommit](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.Source.html#static-codewbrcommitprops))

**Comment by bschwarz** [comment]
Yes, either S3 or Github. Many users of this will probably be on Github, but I think S3 is a good choice too
