### ISSUE TITLE
Admin site login error.

### ISSUE THREAD

**Issue by ameetcateina** [aws-samples/aws-saas-factory-eks-reference-architecture#18]
Whenever the login button of the admin site is hit it throws an "Unauthorized" error. 

This shows up in the network console.
www-authenticate: Bearer realm=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_9N88t77l1, error=INVALID_TOKEN

**Comment by tobuck-aws** [comment]
Hello, and apologies for the late reply? Did your backend services get deployed correctly? Do you see "`https://{domain}/api/amIUp`"?

**Comment by ameetcateina** [comment]
our domain name is e2etechnology.com so when I do a get request to "https://www.e2etechnology.com/api/amIUp"

**Comment by ameetcateina** [comment]
Our domain is e2etechnology.com. When I do a GET request to https://www.e2etechnology.com/api/amIUp I get the
![mypage](https://user-images.githubusercontent.com/78347766/118591982-d03b0780-b7c2-11eb-9b33-86bbe2454be5.png)
 following response. 
Should I hit https://api.e2etechnology.com/api/amIUp instead?
Also during the setup, I get AlreadyExists exception for "eks-ref-arch" key in KMS. Is that a problem?

**Comment by ameetcateina** [comment]
Following APIs return an error 
https://api.e2etechnology.com/tenants
--------------------------------------------------
tenants api error:
{"timestamp":"2021-05-18T08:06:52.320+0000","status":403,"error":"Forbidden","message":"Access Denied","path":"/tenants"}
--------------------------------
https://starfishsetup-adminsite-1usidxvyaz-adminappbucket-1ejppuwttqwr9.auth.us-east-1.amazoncognito.com/oauth2/userInfo
--------------------------------
user info api error:
{"error":"invalid_token","error_description":"Access token does not contain openid scope"}
![unauthorized](https://user-images.githubusercontent.com/78347766/118620076-cd500f00-b7e2-11eb-930a-66c2af9045cb.png)

**Comment by tobuck-aws** [comment]
Ahh, interesting. I think what's happening is that the [Angular auth interceptor](https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/main/clients/Admin/src/app/interceptors/auth.interceptor.ts) is rewriting that `Authorization` header to use the ID Token vs. the Access token. We want to use the ID token when we hit the APIs, but not the `/userinfo` endpoint.
Once [this PR](https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/pull/20) goes in, it'll except the `/userinfo` endpoint and should fix this issue. Once you update, you'll have to redeploy your admin (and probably application) client. I'm not sure why this just now started happening. You can do that via [this script)[https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/main/resources/build_and_upload_admin_site.sh]. You'll have to grab the name of the Admin site bucket out of S3. Hopefully this all made sense. I'll leave this issue open until you confirm it's fixed.

**Comment by tobuck-aws** [comment]
Reopening to await fix confirmation.

**Comment by ameetcateina** [comment]
Thanks a million, it works. But the logout page isn't working. Whenever I hit log out it gets redirected to "https://e2etechnology.com.auth.us-east-1.amazoncognito.com/login?client_id=403oun8l5isf787jlc2v612dtj&response_type=code&redirect_uri=https://admin.e2etechnology.com" and it throws a can't connect error. 
![sneep](https://user-images.githubusercontent.com/78347766/118772524-7b21f300-b8a1-11eb-819d-778c88a151ac.png)

And this is our USer pool setting.
![mysneep](https://user-images.githubusercontent.com/78347766/118772750-b6242680-b8a1-11eb-81c2-86d0a488dcde.png)

**Comment by ameetcateina** [comment]
Thanks Please close
