### ISSUE TITLE
Tenant site Permission denied error.

### ISSUE THREAD

**Issue by ameetcateina** [aws-samples/aws-saas-factory-eks-reference-architecture#21]
The tenants get created but whenever the tenant site is accessed I get Permission denied.
![tenangt](https://user-images.githubusercontent.com/78347766/118828975-5cd8e900-b8db-11eb-8c66-fb8338d01977.png)

browser hit
![aniketsite](https://user-images.githubusercontent.com/78347766/118829037-69f5d800-b8db-11eb-9353-fe6e4fff23c8.png)

**Comment by tobuck-aws** [comment]
That looks like an issue with the CloudFront distribution. Can you make sure the tenant app was deployed to the bucket? Also, if you go to CloudFront service in the console, you can take a look at the CloudFront URL and see if you can get to the site that way.

**Comment by ameetcateina** [comment]
Cannot reach the site via CloudFront URL
![cloudfront](https://user-images.githubusercontent.com/78347766/119077776-906a5f00-ba12-11eb-8427-ef8788b95711.png)
Also, the s3 bucket has the following buckets
![bucket](https://user-images.githubusercontent.com/78347766/119077981-f1923280-ba12-11eb-90da-ca8052064d7c.png)
The first bucket is the code pipeline artifact bucket and the second last bucket is the app bucket which is missing document root file, index.html.
![bucket1](https://user-images.githubusercontent.com/78347766/119078155-4635ad80-ba13-11eb-8774-8a1608b50d39.png)
It just has .svg, .js, .map & font files.

**Comment by ameetcateina** [comment]
The CloudFront URL doesnot work as well.
![cloudfront](https://user-images.githubusercontent.com/78347766/119083081-f0fe9980-ba1c-11eb-9a92-c37e511db8a3.png)
The S3 service has one bucket for the app code pipeline artifact and another bucket namely mystack-appsite-1oradvj5lvl5t-appbucket-1lrn4v7mi0fdi. The second bucket is missing the document root, index.html file. It only has .svg, .js, .map & font files.

**Comment by tobuck-aws** [comment]
It sounds like there may have been an issue during deployment when we build and deploy the App site to the S3 bucket. Please try running the [deploy application script](https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/main/resources/build_and_upload_app_site.sh) again.  

Based on your previous issue, however, I suspect we'll have more given the fact that your `api.{domain}.com/amIUp` wasn't showing up. This is like due to something in the Kubernetes ingress-controller, but we can address that issue if/when you hit it.

**Comment by ameetcateina** [comment]
Thanks, it worked but had to copy build_and_upload_app_site.sh to the parent folder i.e. "aws-saas-factory-eks-reference-architecture" for it to work. Also "deploy.sh" didn't have any reference to "build_and_upload_app_site.sh" so it never executed. 
The health check gives an up status.
![iamup](https://user-images.githubusercontent.com/78347766/119175071-04464f00-ba87-11eb-9081-d80cce22c8fd.png)

**Comment by tobuck-aws** [comment]
The `build_and_upload_app_site.sh` script is referenced from the [`build_and_upload_websites.sh`](https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/main/resources/build_and_upload_websites.sh) script. And that script is called from `deploy.sh`. We have plans to reduce the amount of bash scripting here and try to offload some (most?--hopefully) off to Flux or some other automation mechanism. Stay tuned.
