### ISSUE TITLE
Error while creating a tenant user.

### ISSUE THREAD

**Issue by ameetcateina** [aws-samples/aws-saas-factory-eks-reference-architecture#23]
Getting an error while creating a user on the tenant website.
![oie_transparent](https://user-images.githubusercontent.com/78347766/119214791-1bb52480-bae7-11eb-960e-57f9e36bf2c2.png)
The failed request in the network console is as follows.
![failed request](https://user-images.githubusercontent.com/78347766/119214865-a5fd8880-bae7-11eb-966a-ed9ca4a20bac.png)

**Comment by tobuck-aws** [comment]
This could be a lot of things, but I'd start with basic troubleshooting. The 403 makes me wonder if the token is attached to the outbound request. If it is, then I'd check the logs (`kubectl logs <pod>`) on the service you're trying to hit. Same thing is true of the other issue you reported. Sorry I can't be of more help, but there are too many variables to pinpoint it without some significant time spent troubleshooting.

**Comment by ameetcateina** [comment]
hey its working, sorry for the trouble.

**Comment by tobuck-aws** [comment]
No worries, glad it's working!
