### ISSUE TITLE
Cannot logout the user login

### ISSUE THREAD

**Issue by ashu2490** [aws-samples/aws-saas-factory-eks-reference-architecture#38]
After login whenever the logout button is hit it redirects to this URL "https://e2etechnology.com.auth.us-east-1.amazoncognito.com/login?client_id=403oun8l5isf787jlc2v612dtj&response_type=code&redirect_uri=https://admin.e2etechnology.com" and gives a server not found error.
![SasaFactory]

(https://user-images.githubusercontent.com/89002546/129721289-645bb702-0e3b-4ec0-b582-36bfc8af808d.png)

**Comment by ashu2490** [comment]
Help us to find out the resolution.

**Comment by akshay27395** [comment]
Is any solution for this problem? please help me with the same.

**Comment by tobuck-aws** [comment]
Did you figure this out? Are you users of a deployed version of this project? Or developers?

**Comment by tobuck-aws** [comment]
Duplicate of #22
