### ISSUE TITLE
Access Denied on Admin

### ISSUE THREAD

**Issue by mninawa** [aws-samples/aws-saas-factory-eks-reference-architecture#42]
Im getting the following error when i hit the admin url:
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>3YB6M80****8</RequestId>
<HostId>LhAMMnttn&******</HostId>
</Error>`
what might be the issue? Please help

**Comment by tobuck-aws** [comment]
I suspect that was just a DNI propagation issue. Seems like CloudFront couldn't see the bucket. Did it eventually work?

**Comment by tobuck-aws** [comment]
Assuming this is working... Closing. Please reopen if not.
