### ISSUE TITLE
How to plug this into a CI/CD pipeline?

### ISSUE THREAD

**Issue by SwathiMystery** [aws-samples/aws-saas-factory-eks-reference-architecture#45]
Thank you for providing this reference architecture. It is extremely helpful.

One question though, what would be the right mechanism to plug this into CI/CD pipeline?
Although I understand that setup/deploy scripts will be run before that.

Any pointers will be really helpful. 

Thanks 🙏

**Comment by tobuck-aws** [comment]
HI @SwathiMystery ,
I'm not sure what you're referring to? Do you mean plugging all of the various services into a CI/CD pipeline, so they get automatically deployed as part of an update? Or something else?
