### ISSUE TITLE
Guidance on adding new functionality to the Application app?

### ISSUE THREAD

**Issue by cfregly** [aws-samples/aws-saas-factory-eks-reference-architecture#50]
Is there any guidance on how to add new functionality to the Application?  
 
## Client-side
* Add angular routes (_nav.js, app.routing.js, create new submodule.routing.js)
* invalidate CloudFront cache
* copy dist/ directory to S3 bucket with "appbucket" in the name (use no-copy option to avoid the need to perform the invalidation)
* invalidate CloudFront cache
* update clients/Application/src/environments/environment*.ts (change logos, etc)

## Server-side
* update buildspec.yaml with foo-service.yaml
* create a new foo-service.yaml
* add new service to shared-services/TenantRegistrationService
* add new resources in tenant-stack-master.yaml which references the repo URI's
* add new K8s Service
* update Ingress

## References
* [Reinvent 2021 Talk: Amazon EKS SaaS deep dive: A multi-tenant EKS SaaS solution](https://www.youtube.com/watch?v=tXVLjWjEEwo)

**Comment by ranjith-aws** [comment]
Moved to discussions. https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/discussions/73
