### ISSUE TITLE
Why does the lambda function require events:* permission.

### ISSUE THREAD

**Issue by MissakaI-ObjectOne** [aws-samples/aws-saas-factory-eks-reference-architecture#52]
As in following template relevant to the root-stack. Why does it require all actions to EventBridge?

https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/3fb995a8cd0b655bb51dd89e7a22b9f737844dd3/resources/templates/root-stack.yaml#L51

**Comment by ranjith-aws** [comment]
Hi @MissakaI-ObjectOne Thanks for reaching out. I believe at some point we had plans to push events for building some monitoring and metering around the requests we get, but we didn't pursue that for the initial version. so yes, it makes sense to remove this since we no longer need them. We will get it removed

**Comment by MissakaI-ObjectOne** [comment]
Once I checked the [lambda function](https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/main/functions/source/CfnCrossRegion/lambda_function.py)  I noticed that only following actions are used in related to the EventBridge

https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/3fb995a8cd0b655bb51dd89e7a22b9f737844dd3/functions/source/CfnCrossRegion/lambda_function.py#L251

https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/3fb995a8cd0b655bb51dd89e7a22b9f737844dd3/functions/source/CfnCrossRegion/lambda_function.py#L264

https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/3fb995a8cd0b655bb51dd89e7a22b9f737844dd3/functions/source/CfnCrossRegion/lambda_function.py#L277

https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/3fb995a8cd0b655bb51dd89e7a22b9f737844dd3/functions/source/CfnCrossRegion/lambda_function.py#L291

So based on that following allowing only following actions would do.

```
"events:DeleteRule",
"events:PutTargets",
"events:PutRule",
"events:RemoveTargets"
```

**Comment by ranjith-aws** [comment]
Got it. We will update to those and see if that is enough. Thanks for details here.

**Comment by ranjith-aws** [comment]
Closing this since the new version vNext does not use this Lambda function.
