### ISSUE TITLE
Add User Not Working

### ISSUE THREAD

**Issue by akshay27395** [aws-samples/aws-saas-factory-eks-reference-architecture#53]
Hi I use Admin creds to add a user in the application while doing this process I get a message of user added successfully but cant see the use in the user table and getting the following error log.

UserManagement create user operation failed:com.amazonaws.services.cognitoidp.model.InvalidParameterException: Attribute value for custom:tenant-id must not be null (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: 4cbe046b-af56-4b97-943c-082e0b8cefd6; Proxy: null)

![AWS - EKS Reference Architecture](https://user-images.githubusercontent.com/35006691/157011386-715f10d1-851c-4283-8f4b-f51c936ea263.png)

Will be waiting for the response. Thanks in advance

**Comment by ranjith-aws** [comment]
Hi @akshay27395 We are checking this

**Comment by ranjith-aws** [comment]
I am revisiting this functionality and how it is implemented right now. We will be creating a new PR in the upcoming days for this. Thank you!
