### ISSUE TITLE
Getting "Access denied" when hitting adminpageurl

### ISSUE THREAD

**Issue by oliwerhelsen** [aws-samples/aws-saas-factory-eks-reference-architecture#59]
Hi, 

I keep getting "Access denied" when hitting the admin page URL that I generated in the email sent to me after deployment. Using Vnext branch.

![bild](https://user-images.githubusercontent.com/2570700/187430899-c07a792b-6cac-44be-ba20-6ba96106fe93.png)

Any ideas on this? 

Best regards
Oliwer H.

**Comment by oliwerhelsen** [comment]
No need

**Comment by blueaglet** [comment]
I seem to get the same access denied. How did you resolve the issue? Thanks in advance!

**Comment by oliwerhelsen** [comment]
Sorry @blueaglet I did never solved it. Went for another solution instead.
