### ISSUE TITLE
Error while installing - Python 3.6 no longer supported

### ISSUE THREAD

**Issue by lal-verma** [aws-samples/aws-saas-factory-eks-reference-architecture#60]
Getting an error while installing the reference solution. Here's the snapshot of AWS CloudFormation event which got failed. Looks like  its trying to deploy lambda function on the runtime python 3.6 which is no longer available with AWS lambda. 

<img width="842" alt="Screen Shot 2022-09-14 at 3 55 09 PM" src="https://user-images.githubusercontent.com/32193810/190498614-4fa16644-9155-4a22-a8c5-d9a64b4b6ed9.png">

**Comment by ranjith-aws** [comment]
vNext is not using this Python lambda function, so we won't have this issue anymore. So closing this.
