### ISSUE TITLE
Error while tenant registration: EKS namespace is empty

### ISSUE THREAD

**Issue by lal-verma** [aws-samples/aws-saas-factory-eks-reference-architecture#63]
EKS namespace is empty while tenant registration.

more investigation revealed that the tag/untag permissions are missing in the script - update-eks-node-permissions.sh

**Comment by ranjith-aws** [comment]
This is in the main branch, correct? Not in vNext?

**Comment by lal-verma** [comment]
Its in the main branch.

**Comment by ranjith-aws** [comment]
Thanks. We are moving the vNext branch to main, where we dont have this issue. So closing this.
