### ISSUE TITLE
Time Out on during Stack Formation

### ISSUE THREAD

**Issue by Ben2353** [aws-samples/aws-saas-factory-eks-reference-architecture#67]
Time Out on CloudFormation during CloudFormationAppCert:

CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [81bc180d-44d8-48f9-892c-99c12dda17e4]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

I've had a look at 'lambda_function.py' but the cfn module is not imported, any thoughts?

**Comment by ranjithkraman** [comment]
Hi @Ben2353 I suspect I know what is happening here. Let me run a test and get back. Meanwhile, we are working on upgrading this project to the next version. There is a branch called vNext which we are very close to launch (working on couple of outstanding issues), which shouldn't have this particular problem. So when you get a chance, please try that out. There are 2 modes in which you can run vNext - with and without domain. For now, I recommend trying the "without domain" option.  I will get back to you in this specific issue as well.

**Comment by Ben2353** [comment]
Fantastic, thanks Ranjith!
I'll give vNext a go and let you know how it works out
