### ISSUE TITLE
Error provisioning tenant from Admin site - vnext

### ISSUE THREAD

**Issue by thecount1986** [aws-samples/aws-saas-factory-eks-reference-architecture#69]
<img width="1120" alt="Screen Shot 2022-11-13 at 4 38 17 PM" src="https://user-images.githubusercontent.com/13307605/201548415-46e6dd4b-c1d1-4c3f-9b61-b841519f842f.png">

**Comment by ranjith-aws** [comment]
Hi @thecount1986 This is resolved now. This was a timing issue, almost a race condition between when the namespace was still getting created but some how that namespace was being already referenced in a subsequent part of the code. Please test and let us know.

**Comment by thecount1986** [comment]
When I go to EKS it is telling me I don't have access to the cluster. Any Idea about this? Where should we add the Kubernetes RBAC permission? 
<img width="1313" alt="Screen Shot 2022-12-09 at 7 32 21 PM" src="https://user-images.githubusercontent.com/13307605/206822123-c81f0dcd-e99d-4796-a7e6-707efc0e0d4b.png">

**Comment by ranjith-aws** [comment]
@thecount1986 Could you try the steps described in this link https://www.eksworkshop.com/030_eksctl/console/ and see if that helps resolve?
