### ISSUE TITLE
Issue when running setup.sh with importing key-pair to ec2 service

### ISSUE THREAD

**Issue by simith** [aws-samples/aws-saas-factory-eks-reference-architecture#71]
fileb:// needs to be used instead of file:// using AWS CLI v2

AWS CLI version: **aws-cli/2.7.1 Python/3.9.11 Linux/4.14.287-215.504.amzn2.x86_64 exe/x86_64.amz**n.2

The following command works with the updated **fileb://**
aws ec2 import-key-pair --key-name "eks-saas" --public-key-material file**b**://~/.ssh/id_rsa.pub

**Comment by ranjith-aws** [comment]
Hi @simith Thanks for reporting this. We are currently in the process of moving a new set of features and updates to this project. This is all available in the vnext branch. Could you please try there and let us know. Also, the above command is not required anymore, so you will not run in to that specific issue. Please let us know how it goes.

**Comment by ranjith-aws** [comment]
This has been fixed. Closing issue
