### ISSUE TITLE
Failed to Provision tenant

### ISSUE THREAD

**Issue by biglocalcode** [aws-samples/aws-saas-factory-eks-reference-architecture#72]
Hello Team,
![image](https://user-images.githubusercontent.com/97698105/204368755-f6e15aeb-1229-4de7-af47-2075754cf93d.png)
I have been this "there has ben an error provisioning your tenant" from the main branch.

What am I missing?

**Comment by ranjith-aws** [comment]
Hi @biglocalcode Sorry about the delayed response. I am checking this

**Comment by ranjith-aws** [comment]
@biglocalcode We have been working on adding new features and some major updates to this project. They are all available in the vnext branch. You will find detailed instructions in the vnext branch on how to get it setup and running. Also, as part of the new update, you wouldn't need to bring a custom domain anymore. And I just tested provisioning a new tenant, and it worked fine. So, please give it a try and let me know, if you still see this issue.

Ranjith
