### ISSUE TITLE
No SaaSClusterConfigCommand in CFN Outputs

### ISSUE THREAD

**Issue by abianche** [aws-samples/aws-saas-factory-eks-reference-architecture#89]
Hi!
In the following line:
https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture/blob/3666ab8e284bbf1de71899b068f0b5b93949dd0e/README.md?plain=1#L92

it states that an output for SaaSClusterConfigCommand should be available in the Outputs of the cluster template, but I actually do not see that.
I am struggling a bit to get the kubeconfig updated so that I can manage the cluster from the CLI.
I just run `aws eks update-kubeconfig --region eu-central-1 --name EKSSaaS` but then for the commands I keep getting `error: You must be logged in to the server (Unauthorized)`.

Thanks for the help!

**Comment by ranjith-aws** [comment]
Fixed with #98
